
export const ID_MEDECIN = "ID_MEDECIN";
export const ID_PROFIL = "ID_PROFIL";
export const HEURE_RESERVER = "HEURE_RESERVER";
export const HEURE_DISPONIBLE = "HEURE_DISPONIBLE";
export const RESULTAT_RECHERCHE = "RESULTAT_RECHERCHE";
export const NBR_MSGNONLU = "NBR_MSGNONLU";
export const ROLE = "ROLE";